flutter 2.0으로 마이그레이션
iamport/iamport_flutter pull request #27
Opened 2021-05-15 11:41 UTC by anymate98

- flutter v2에 대응
- 웹뷰 플러그인 교체
- 안드로이드 플러그인 의존성 제거
- 예제 프로그램의 androidX 지원 추가
- 스마일페이 쿠키 문제 해결
- 플랫폼별 앱 실행과정 통합

2021-05-17 10:16 UTC, kjh5833 requested changes

2021-05-17 10:55 UTC, anymate98 commented on lib/Iamport_certification.dart
> +  final String? userCode;
dart cli에 자동 마이그레이션 기능이 있어서 돌렸더니 저렇게 되었군요
다른 필드들도 한번씩 다시 살펴보겠습니다

2021-05-17 11:03 UTC, anymate98 commented on lib/model/iamport_url.dart
> +      } else {
else는 빼려고도 생각해봤는데, `intent:[...]#Intent;[...];end` 안에 패키지 정보가 없는 케이스가 오거나 `[scheme]://[...]`과 같이 iOS 스타일의 url이 들어온다면 다른 방식으로 플레이스토어 링크를 제공해야 할 수단이 필요할 것 같아 남겨두었습니다. 뱅크페이가 실제로 그러기 때문에 기존 코드에도 scheme 및 패키지 이름이 하드코딩되어있는거로 생각되었고요.
지금까지 테스트해본 결과 ISP와 뱅크페이 말고는 패키지가 주어지지 않는 케이스는 없는것 같긴 하지만 만약을 위해 남겨두어야 한다고 생각하는데 어떻게 생각하시나요?

2021-05-17 11:15 UTC, anymate98 commented on lib/model/iamport_url.dart
> +  static const String redirectUrl = 'http://localhost/iamport';
이왕이면 다른곳도 한글자만 쓰니까 ../iamport/f 라고 쓰는게 어떨까요?
그리고 플랫폼 키워드는 서버에서 날라오는 것인지 아니면 직접 코드에 집어넣어야 하는건지 궁금합니다

2021-05-17 11:21 UTC, anymate98 commented on lib/model/iamport_validation.dart
> +  IamportValidation(String? userCode, PaymentData? data, Function? callback) {
이부분도 dart가 자동으로 고쳐줘서 자세히 살펴보지 못했군요. 다시 한번 봐보겠습니다.
리뷰 감사합니다~

2021-05-18 00:47 UTC, kjh5833 commented on lib/model/iamport_url.dart
> +  static const String redirectUrl = 'http://localhost/iamport';
그냥 저희 구분을 위한 룰입니다 ㅋㅋ 나중에 보면 전부 localhost 로 써있어서 
기술문의 왔을때 이 사람이 무슨 sdk 를 썼는지 꼭 물어봐야 하더라구오.
하드코딩으로 써주시면 좋을 것 같아요!

2021-05-18 00:49 UTC, kjh5833 commented on lib/model/iamport_url.dart
> +      } else {
아하! 밑의 switch 는 놔두고, else 문만 빠지면 될 것 같다는 의미였습니당.

2021-05-31 06:13 UTC, kjh5833 commented
팝업 처리가 필요합니다.

예시로 아래 케이스에서 팝업이 뜹니다.
- 모빌리언스, 휴대폰 소액결제 -> 우측상단 x 버튼클릭
- kcp, 신용카드결제(10만원 이상) -> 쿠폰, 할부 미선택 후 다음 클릭

네이티브 SDK 에서는 아래와 같이 처리하고 있는데요.
플러터 웹뷰 플러그인에서도 지원 방법을 찾아야 할 듯 싶습니다.

- ***Android 의 경우 아래 코드 참고***

[https://github.com/iamport/iamport-android/blob/a8e5d378375c1d0461ba790d3376f34e019d095d/sdk/src/main/java/com/iamport/sdk/domain/IamportWebChromeClient.kt#L10](https://github.com/iamport/iamport-android/blob/a8e5d378375c1d0461ba790d3376f34e019d095d/sdk/src/main/java/com/iamport/sdk/domain/IamportWebChromeClient.kt#L10)

[https://github.com/iamport/iamport-android/blob/a8e5d378375c1d0461ba790d3376f34e019d095d/sdk/src/main/java/com/iamport/sdk/presentation/activity/WebViewActivity.kt#L237](https://github.com/iamport/iamport-android/blob/a8e5d378375c1d0461ba790d3376f34e019d095d/sdk/src/main/java/com/iamport/sdk/presentation/activity/WebViewActivity.kt#L237)

- ***iOS 의 경우 아래 코드 참고***

[https://github.com/iamport/iamport-ios/blob/d401eb3c360cf7a2e0f30a1c9a873d05f498822f/iamport-ios/Classes/Presentation/WebViewController.swift#L403](https://github.com/iamport/iamport-ios/blob/d401eb3c360cf7a2e0f30a1c9a873d05f498822f/iamport-ios/Classes/Presentation/WebViewController.swift#L403)

2021-06-02 03:18 UTC, kjh5833 approved these changes

2021-06-02 03:19 UTC, kjh5833 commented
수고하셨어용~~!

2021-06-02 07:03 UTC, anymate98 commented
@SoleeChoi 버전 업그레이드 한번만 확인 부탁드립니다

2021-06-04 00:13 UTC, merged