우리WON카드 추가
iamport/iamport_flutter pull request #31
Opened 2021-06-21 03:24 UTC by anymate98

2021-06-22 11:47 UTC, kjh5833 commented
아하 코드는 문제 없는 것 같아요~~ 두가지 질문이 있습니다.
1. 혹시 우리 WON 카드에서 결제 해보셨나요? (앱 띄워지는지라도)
2. L.POINT (scheme : lmslpay, id : id473250588) 는 PR 따로 올리실건지 궁금합니다~!
요거만 알게되면 approve 할게요 ㅋㅋ

2021-06-23 03:10 UTC, kjh5833 approved these changes

2021-06-23 13:20 UTC, kjh5833 approved these changes

2021-06-24 11:24 UTC, SoleeChoi requested changes

2021-07-08 06:54 UTC, SoleeChoi approved these changes

2021-07-08 06:55 UTC, SoleeChoi commented
@anymate98 안녕하세요 하루 실제로 안드로이드에서 구동해본 결과 아래 내용에 대해 정상적으로 처리되고 있는 것을 확인하였습니다.

- 롯데 L.Point
- 우리 Won 카드
- 농협 일반결제

다만, develop 브랜치에 commit을 하신 것으로 확인되는데
향후에는 feature 브랜치를 따서 작업 해주시길 부탁드립니다.

수고 많으셨습니다! 감사합니다 :)

2021-07-09 01:19 UTC, merged